### ISSUE TITLE
Authentication token

### ISSUE THREAD

**Issue by jvence** [etiennea/phonegap-twitter-plugin#7]
Not sure if this makes much sense but my app will send the Twitter token to the server which will make some calls directly to twitter. Can this plugin pass an authentication token?

**Comment by etiennea** [comment]
Yes you can do it with this plugin. 

Have a look at this old plugin https://github.com/PatrickHeneise/SocialAuthenticationPlugin that does only that. You just need to call 

```
TW_API_ROOT "/oauth/access_token"
```

https://dev.twitter.com/oauth/overview
